### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by YeonV** [dhulme/multitrack-player#35]
Hi master!

Thank you soo much for this wonderful project!
Would you still be intrested in this project?
I never did vuejs in the past and tried out some stuff:
![image](https://github.com/dhulme/multitrack-player/assets/28861537/5308308f-faa2-4df9-bfee-fceb938f85c6)

**Comment by dhulme** [comment]
Hello! Glad it's been useful for you. It's no longer active unfortunately. Nice! Send me a link to your code?

**Comment by YeonV** [comment]
i have not uploaded any code to github yet. as i said, its the first time i tried vue. i can share all my files with you ofc. since im unable to recreate this multi-track player in react, i would like to include a minimalistic production version of the player only. no metronom, no midi, just the player.
![image](https://github.com/dhulme/multitrack-player/assets/28861537/40f45e10-92d8-4a94-abeb-83862c37dc6a)

It works okay by loading the vueapp in an iframe of my react app:

i saw u are kind of using indexedDb. did you plan to store the audio files in there?
if so, maybe i can load them into the indexedDb from react, so the vue player can initialize with loaded files.

also i tried to wrap an electron app around the vue app, but i failed hard, so if i can make those files work via indexedDb i can wrap my react app with electron to provide the files directly.

Offtopic (but since you are a music guy):
i found a wonderful project called stemroller, which utilized demucs to seperate music files into drums, vocal, etc.

They dont have a multitrack player, so i thought if i could either recreate this in react, or make this indexedDb thing together with electron and react, then they could have it as an addon...

**Comment by YeonV** [comment]
here is the alpha of the react recreation:
https://yeonv.github.io/stemplayer/

**Comment by dhulme** [comment]
The actual loading/analysis/playing isn't really vue code, more JS, so I would probably just look at that code and migrate that bit to react. Thanks for the info about stemroller - I hadn't heard of that!
